name: Keep Me Alive

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:

jobs:
  keep-active:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a commit to mark activity
      run: |
        date > activity-log.txt
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add activity-log.txt
        git commit -m "look i'm alive"

    - name: Push changes
      run: git push
